name: StarLift
version: 1.0
description: Fahrstuhl plugin
author: Aubli
main: me.Aubli.StarLift

commands:
    sl:
       description: StarLift Befehle!
       usage: |
              /<command> tool
              /<command> list
              /<command> lift [liftID] [dest]