name: StarLift
version: 0.8
description: Fahrstuhl plugin
author: Aubli
main: me.Aubli.StarLift.StarLift

commands:
    sl:
       description: StarLift Befehle!
       usage: |
              /<command> tool
              /<command> lift [liftID] [dest]